/**
 * Financial and number formatting utilities with Indian numbering system.
 */

/**
 * Calculates exact total amount in Rupees using integer paisa to eliminate floating point issues.
 * @param quantityLitres e.g. 8.5
 * @param ratePerLitre e.g. 52.00
 * @returns rounded exact Rupee amount (number with up to 2 decimal places)
 */
export function calculateAmount(quantityLitres: number, ratePerLitre: number): number {
  if (isNaN(quantityLitres) || isNaN(ratePerLitre) || quantityLitres < 0 || ratePerLitre < 0) {
    return 0;
  }
  // Convert to paisa: quantity * (rate * 100) rounded
  const paisa = Math.round(quantityLitres * (ratePerLitre * 100));
  return paisa / 100;
}

/**
 * Formats a number to Indian Rupee currency format (e.g., ₹1,24,850 or ₹7,124.50).
 * Handles Indian numbering comma rules (e.g. 1,00,000 for 1 Lakh).
 */
export function formatRupees(amount: number, showDecimals: boolean = false): string {
  if (isNaN(amount)) return '₹0';
  
  const isNegative = amount < 0;
  const absAmount = Math.abs(amount);
  
  const options: Intl.NumberFormatOptions = {
    style: 'currency',
    currency: 'INR',
    minimumFractionDigits: showDecimals ? 2 : (absAmount % 1 === 0 ? 0 : 2),
    maximumFractionDigits: 2
  };

  const formatter = new Intl.NumberFormat('en-IN', options);
  let formatted = formatter.format(absAmount);
  
  // Clean up any extra spaces if generated by some browser engines
  formatted = formatted.replace(/\s+/g, ' ').trim();

  return isNegative ? `-${formatted}` : formatted;
}

/**
 * Formats milk quantity with 'L' suffix.
 * e.g. 8 -> "8 L", 8.5 -> "8.5 L", 10.25 -> "10.25 L"
 */
export function formatLitres(litres: number): string {
  if (isNaN(litres)) return '0 L';
  
  // Format up to 2 decimal places, trimming trailing zeroes
  const formatted = parseFloat(litres.toFixed(2)).toString();
  return `${formatted} L`;
}

/**
 * Parses user input string into safe positive float quantity or 0.
 */
export function parseQuantityInput(input: string | number): number {
  if (typeof input === 'number') {
    return isNaN(input) || input < 0 ? 0 : parseFloat(input.toFixed(2));
  }
  const clean = input.trim();
  if (!clean) return 0;
  const val = parseFloat(clean);
  if (isNaN(val) || val < 0) return 0;
  return parseFloat(val.toFixed(2));
}

/**
 * Formats ISO timestamp to Indian format with time:
 * "30 Aug 2026, 07:30 AM"
 */
export function formatTimestampIST(isoString: string): string {
  if (!isoString) return '';
  try {
    const date = new Date(isoString);
    return new Intl.DateTimeFormat('en-IN', {
      timeZone: 'Asia/Kolkata',
      day: 'numeric',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      hour12: true
    }).format(date);
  } catch (e) {
    return isoString;
  }
}
